<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('municipios')->insert([
            ['codigo_municipio' => 1, 'id_departamento' => 1, 'nombre' => 'LA CEIBA'],
            ['codigo_municipio' => 2, 'id_departamento' => 1, 'nombre' => 'EL PORVENIR'],
            ['codigo_municipio' => 3, 'id_departamento' => 1, 'nombre' => 'ESPARTA'],
            ['codigo_municipio' => 4, 'id_departamento' => 1, 'nombre' => 'JUTIAPA'],
            ['codigo_municipio' => 5, 'id_departamento' => 1, 'nombre' => 'LA MASICA'],
            ['codigo_municipio' => 6, 'id_departamento' => 1, 'nombre' => 'SAN FRANCISCO'],
            ['codigo_municipio' => 7, 'id_departamento' => 1, 'nombre' => 'TELA'],
            ['codigo_municipio' => 8, 'id_departamento' => 1, 'nombre' => 'ARIZONA'],
            ['codigo_municipio' => 1, 'id_departamento' => 2, 'nombre' => 'TRUJILLO'],
            ['codigo_municipio' => 2, 'id_departamento' => 2, 'nombre' => 'SANTA ROSA DE AGUAN'],
            ['codigo_municipio' => 3, 'id_departamento' => 2, 'nombre' => 'IRIONA'],
            ['codigo_municipio' => 4, 'id_departamento' => 2, 'nombre' => 'LIMON'],
            ['codigo_municipio' => 5, 'id_departamento' => 2, 'nombre' => 'SANTA FE'],
            ['codigo_municipio' => 6, 'id_departamento' => 2, 'nombre' => 'SONAGUERA'],
            ['codigo_municipio' => 7, 'id_departamento' => 2, 'nombre' => 'TOCOA'],
            ['codigo_municipio' => 8, 'id_departamento' => 2, 'nombre' => 'SABA'],
            ['codigo_municipio' => 9, 'id_departamento' => 2, 'nombre' => 'BALFATE'],
            ['codigo_municipio' => 10, 'id_departamento' => 2, 'nombre' => 'BONITO ORIENTAL'],
            ['codigo_municipio' => 1, 'id_departamento' => 3, 'nombre' => 'COMAYAGUA'],
            ['codigo_municipio' => 2, 'id_departamento' => 3, 'nombre' => 'AJUTERIQUE'],
            ['codigo_municipio' => 3, 'id_departamento' => 3, 'nombre' => 'EL ROSARIO'],
            ['codigo_municipio' => 4, 'id_departamento' => 3, 'nombre' => 'ESQUIAS'],
            ['codigo_municipio' => 5, 'id_departamento' => 3, 'nombre' => 'HUMUYA'],
            ['codigo_municipio' => 6, 'id_departamento' => 3, 'nombre' => 'LA LIBERTAD'],
            ['codigo_municipio' => 7, 'id_departamento' => 3, 'nombre' => 'LAMANI'],
            ['codigo_municipio' => 8, 'id_departamento' => 3, 'nombre' => 'LA TRINIDAD'],
            ['codigo_municipio' => 9, 'id_departamento' => 3, 'nombre' => 'LEJAMANI'],
            ['codigo_municipio' => 10, 'id_departamento' => 3, 'nombre' => 'MEAMBAR'],
            ['codigo_municipio' => 11, 'id_departamento' => 3, 'nombre' => 'MINAS DE ORO'],
            ['codigo_municipio' => 12, 'id_departamento' => 3, 'nombre' => 'OJO DE AGUA'],
            ['codigo_municipio' => 13, 'id_departamento' => 3, 'nombre' => 'SAN JERONIMO'],
            ['codigo_municipio' => 14, 'id_departamento' => 3, 'nombre' => 'SAN JOSE DE COMAYAGUA'],
            ['codigo_municipio' => 15, 'id_departamento' => 3, 'nombre' => 'SAN JOSE DEL POTRERO'],
            ['codigo_municipio' => 16, 'id_departamento' => 3, 'nombre' => 'SAN SEBASTIAN'],
            ['codigo_municipio' => 17, 'id_departamento' => 3, 'nombre' => 'SIGUATEPEQUE'],
            ['codigo_municipio' => 18, 'id_departamento' => 3, 'nombre' => 'VILLA DE SAN ANTONIO'],
            ['codigo_municipio' => 19, 'id_departamento' => 3, 'nombre' => 'SAN LUIS'],
            ['codigo_municipio' => 20, 'id_departamento' => 3, 'nombre' => 'LAS LAJAS'],
            ['codigo_municipio' => 21, 'id_departamento' => 3, 'nombre' => 'TAULABE'],
            ['codigo_municipio' => 1, 'id_departamento' => 4, 'nombre' => 'SANTA ROSA DE COPAN'],
            ['codigo_municipio' => 2, 'id_departamento' => 4, 'nombre' => 'CABAÑAS'],
            ['codigo_municipio' => 3, 'id_departamento' => 4, 'nombre' => 'CONCEPCION'],
            ['codigo_municipio' => 4, 'id_departamento' => 4, 'nombre' => 'COPAN RUINAS'],
            ['codigo_municipio' => 5, 'id_departamento' => 4, 'nombre' => 'CORQUIN'],
            ['codigo_municipio' => 6, 'id_departamento' => 4, 'nombre' => 'CUCUYAGUA'],
            ['codigo_municipio' => 7, 'id_departamento' => 4, 'nombre' => 'DOLORES'],
            ['codigo_municipio' => 8, 'id_departamento' => 4, 'nombre' => 'DULCE NOMBRE'],
            ['codigo_municipio' => 9, 'id_departamento' => 4, 'nombre' => 'EL PARAISO'],
            ['codigo_municipio' => 10, 'id_departamento' => 4, 'nombre' => 'FLORIDA'],
            ['codigo_municipio' => 11, 'id_departamento' => 4, 'nombre' => 'LA UNION'],
            ['codigo_municipio' => 12, 'id_departamento' => 4, 'nombre' => 'NUEVA ARCADIA'],
            ['codigo_municipio' => 13, 'id_departamento' => 4, 'nombre' => 'SAN ANTONIO'],
            ['codigo_municipio' => 14, 'id_departamento' => 4, 'nombre' => 'SAN JERONIMO'],
            ['codigo_municipio' => 15, 'id_departamento' => 4, 'nombre' => 'SAN JOSE DE COPAN'],
            ['codigo_municipio' => 16, 'id_departamento' => 4, 'nombre' => 'SAN JOSE DE OPOA'],
            ['codigo_municipio' => 17, 'id_departamento' => 4, 'nombre' => 'SAN NICOLAS'],
            ['codigo_municipio' => 18, 'id_departamento' => 4, 'nombre' => 'SAN PEDRO'],
            ['codigo_municipio' => 19, 'id_departamento' => 4, 'nombre' => 'SANTA RITA DE COPAN'],
            ['codigo_municipio' => 20, 'id_departamento' => 4, 'nombre' => 'TRINIDAD DE COPAN'],
            ['codigo_municipio' => 21, 'id_departamento' => 4, 'nombre' => 'VERACRUZ'],
            ['codigo_municipio' => 22, 'id_departamento' => 4, 'nombre' => 'SAN AGUSTIN'],
            ['codigo_municipio' => 23, 'id_departamento' => 4, 'nombre' => 'LA ENTRADA'],
            ['codigo_municipio' => 24, 'id_departamento' => 4, 'nombre' => 'LA JIGUA'],
            ['codigo_municipio' => 1, 'id_departamento' => 5, 'nombre' => 'SAN PEDRO SULA'],
            ['codigo_municipio' => 2, 'id_departamento' => 5, 'nombre' => 'CHOLOMA'],
            ['codigo_municipio' => 3, 'id_departamento' => 5, 'nombre' => 'OMOA'],
            ['codigo_municipio' => 4, 'id_departamento' => 5, 'nombre' => 'PIMIENTA'],
            ['codigo_municipio' => 5, 'id_departamento' => 5, 'nombre' => 'POTRERILLOS'],
            ['codigo_municipio' => 6, 'id_departamento' => 5, 'nombre' => 'PUERTO CORTES'],
            ['codigo_municipio' => 7, 'id_departamento' => 5, 'nombre' => 'SAN ANTONIO DE CORTES'],
            ['codigo_municipio' => 8, 'id_departamento' => 5, 'nombre' => 'SAN FRANCISCO DE YOJOA'],
            ['codigo_municipio' => 9, 'id_departamento' => 5, 'nombre' => 'SAN MANUEL'],
            ['codigo_municipio' => 10, 'id_departamento' => 5, 'nombre' => 'SANTA CRUZ DE YOJOA'],
            ['codigo_municipio' => 11, 'id_departamento' => 5, 'nombre' => 'VILLANUEVA'],
            ['codigo_municipio' => 12, 'id_departamento' => 5, 'nombre' => 'LA LIMA'],
            ['codigo_municipio' => 1, 'id_departamento' => 6, 'nombre' => 'CHOLUTECA'],
            ['codigo_municipio' => 2, 'id_departamento' => 6, 'nombre' => 'APACILAGUA'],
            ['codigo_municipio' => 3, 'id_departamento' => 6, 'nombre' => 'CONCEPCION DE MARIA'],
            ['codigo_municipio' => 4, 'id_departamento' => 6, 'nombre' => 'DUYURE'],
            ['codigo_municipio' => 5, 'id_departamento' => 6, 'nombre' => 'EL CORPUS'],
            ['codigo_municipio' => 6, 'id_departamento' => 6, 'nombre' => 'EL TRIUNFO'],
            ['codigo_municipio' => 7, 'id_departamento' => 6, 'nombre' => 'MOROLICA'],
            ['codigo_municipio' => 8, 'id_departamento' => 6, 'nombre' => 'NAMASIGUE'],
            ['codigo_municipio' => 9, 'id_departamento' => 6, 'nombre' => 'OROCUINA'],
            ['codigo_municipio' => 10, 'id_departamento' => 6, 'nombre' => 'PESPIRE'],
            ['codigo_municipio' => 11, 'id_departamento' => 6, 'nombre' => 'SAN ANTONIO DE FLORES'],
            ['codigo_municipio' => 12, 'id_departamento' => 6, 'nombre' => 'SAN ISIDRO'],
            ['codigo_municipio' => 13, 'id_departamento' => 6, 'nombre' => 'SAN JOSE'],
            ['codigo_municipio' => 14, 'id_departamento' => 6, 'nombre' => 'SAN MARCOS DE COLON'],
            ['codigo_municipio' => 15, 'id_departamento' => 6, 'nombre' => 'SANTA ANA DE YUSGUARE'],
            ['codigo_municipio' => 16, 'id_departamento' => 6, 'nombre' => 'MARCOVIA'],
            ['codigo_municipio' => 1, 'id_departamento' => 7, 'nombre' => 'YUSCARAN'],
            ['codigo_municipio' => 2, 'id_departamento' => 7, 'nombre' => 'ALAUCA'],
            ['codigo_municipio' => 3, 'id_departamento' => 7, 'nombre' => 'DANLI'],
            ['codigo_municipio' => 4, 'id_departamento' => 7, 'nombre' => 'EL PARAISO'],
            ['codigo_municipio' => 5, 'id_departamento' => 7, 'nombre' => 'GUINOPE'],
            ['codigo_municipio' => 6, 'id_departamento' => 7, 'nombre' => 'JACALEAPA'],
            ['codigo_municipio' => 7, 'id_departamento' => 7, 'nombre' => 'LIURE'],
            ['codigo_municipio' => 8, 'id_departamento' => 7, 'nombre' => 'MOROCELI'],
            ['codigo_municipio' => 9, 'id_departamento' => 7, 'nombre' => 'OROPOLI'],
            ['codigo_municipio' => 10, 'id_departamento' => 7, 'nombre' => 'POTRERILLOS'],
            ['codigo_municipio' => 11, 'id_departamento' => 7, 'nombre' => 'SAN ANTONIO DE FLORES'],
            ['codigo_municipio' => 12, 'id_departamento' => 7, 'nombre' => 'SAN LUCAS'],
            ['codigo_municipio' => 13, 'id_departamento' => 7, 'nombre' => 'SAN MATIAS'],
            ['codigo_municipio' => 14, 'id_departamento' => 7, 'nombre' => 'SOLEDAD'],
            ['codigo_municipio' => 15, 'id_departamento' => 7, 'nombre' => 'TEUPASENTI'],
            ['codigo_municipio' => 16, 'id_departamento' => 7, 'nombre' => 'TEXIGUAT'],
            ['codigo_municipio' => 17, 'id_departamento' => 7, 'nombre' => 'VADO ANCHO'],
            ['codigo_municipio' => 18, 'id_departamento' => 7, 'nombre' => 'YAUYUPE'],
            ['codigo_municipio' => 19, 'id_departamento' => 7, 'nombre' => 'TROJES'],
            ['codigo_municipio' => 1, 'id_departamento' => 8, 'nombre' => 'TEGUCIGALPA M.D.C.'],
            ['codigo_municipio' => 2, 'id_departamento' => 8, 'nombre' => 'ALUBAREN'],
            ['codigo_municipio' => 3, 'id_departamento' => 8, 'nombre' => 'CEDROS'],
            ['codigo_municipio' => 4, 'id_departamento' => 8, 'nombre' => 'CURAREN'],
            ['codigo_municipio' => 5, 'id_departamento' => 8, 'nombre' => 'GUAIMACA'],
            ['codigo_municipio' => 6, 'id_departamento' => 8, 'nombre' => 'LA LIBERTAD'],
            ['codigo_municipio' => 7, 'id_departamento' => 8, 'nombre' => 'LA VENTA'],
            ['codigo_municipio' => 8, 'id_departamento' => 8, 'nombre' => 'LEPATERIQUE'],
            ['codigo_municipio' => 9, 'id_departamento' => 8, 'nombre' => 'MARAITA'],
            ['codigo_municipio' => 10, 'id_departamento' => 8, 'nombre' => 'MARALE'],
            ['codigo_municipio' => 11, 'id_departamento' => 8, 'nombre' => 'NUEVA ARMENIA'],
            ['codigo_municipio' => 12, 'id_departamento' => 8, 'nombre' => 'OJOJONA'],
            ['codigo_municipio' => 13, 'id_departamento' => 8, 'nombre' => 'ORICA'],
            ['codigo_municipio' => 14, 'id_departamento' => 8, 'nombre' => 'REITOCA'],
            ['codigo_municipio' => 15, 'id_departamento' => 8, 'nombre' => 'SABANAGRANDE'],
            ['codigo_municipio' => 16, 'id_departamento' => 8, 'nombre' => 'SAN ANTONIO DE ORIENTE'],
            ['codigo_municipio' => 17, 'id_departamento' => 8, 'nombre' => 'SAN BUENAVENTURA'],
            ['codigo_municipio' => 18, 'id_departamento' => 8, 'nombre' => 'SAN JUAN DE FLORES'],
            ['codigo_municipio' => 19, 'id_departamento' => 8, 'nombre' => 'SAN MIGUELITO'],
            ['codigo_municipio' => 20, 'id_departamento' => 8, 'nombre' => 'SANTA ANA'],
            ['codigo_municipio' => 21, 'id_departamento' => 8, 'nombre' => 'SANTA LUCIA'],
            ['codigo_municipio' => 22, 'id_departamento' => 8, 'nombre' => 'TALANGA'],
            ['codigo_municipio' => 23, 'id_departamento' => 8, 'nombre' => 'TATUMBLA'],
            ['codigo_municipio' => 24, 'id_departamento' => 8, 'nombre' => 'VALLE DE ANGELES'],
            ['codigo_municipio' => 25, 'id_departamento' => 8, 'nombre' => 'VILLA DE SAN FRANCISCO'],
            ['codigo_municipio' => 26, 'id_departamento' => 8, 'nombre' => 'SAN IGNACIO'],
            ['codigo_municipio' => 27, 'id_departamento' => 8, 'nombre' => 'EL PORVENIR'],
            ['codigo_municipio' => 28, 'id_departamento' => 8, 'nombre' => 'VALLECILLO'],
            ['codigo_municipio' => 29, 'id_departamento' => 8, 'nombre' => 'COMAYAGUELA'],
            ['codigo_municipio' => 1, 'id_departamento' => 9, 'nombre' => 'PUERTO LEMPIRA'],
            ['codigo_municipio' => 2, 'id_departamento' => 9, 'nombre' => 'POLICARPO BONILLA'],
            ['codigo_municipio' => 3, 'id_departamento' => 9, 'nombre' => 'BRUS LAGUNA'],
            ['codigo_municipio' => 4, 'id_departamento' => 9, 'nombre' => 'JUAN FRANCISCO BULNES'],
            ['codigo_municipio' => 5, 'id_departamento' => 9, 'nombre' => 'VILLEDA MORALES'],
            ['codigo_municipio' => 6, 'id_departamento' => 9, 'nombre' => 'WAMPUSIRPI'],
            ['codigo_municipio' => 1, 'id_departamento' => 10, 'nombre' => 'LA ESPERANZA'],
            ['codigo_municipio' => 2, 'id_departamento' => 10, 'nombre' => 'CAMASCA'],
            ['codigo_municipio' => 3, 'id_departamento' => 10, 'nombre' => 'COLOMONCAGUA'],
            ['codigo_municipio' => 4, 'id_departamento' => 10, 'nombre' => 'CONCEPCION'],
            ['codigo_municipio' => 5, 'id_departamento' => 10, 'nombre' => 'DOLORES'],
            ['codigo_municipio' => 6, 'id_departamento' => 10, 'nombre' => 'INTIBUCA'],
            ['codigo_municipio' => 7, 'id_departamento' => 10, 'nombre' => 'JESUS DE OTORO'],
            ['codigo_municipio' => 8, 'id_departamento' => 10, 'nombre' => 'MAGDALENA'],
            ['codigo_municipio' => 9, 'id_departamento' => 10, 'nombre' => 'MASAGUARA'],
            ['codigo_municipio' => 10, 'id_departamento' => 10, 'nombre' => 'SAN ANTONIO'],
            ['codigo_municipio' => 11, 'id_departamento' => 10, 'nombre' => 'SAN ISIDRO'],
            ['codigo_municipio' => 12, 'id_departamento' => 10, 'nombre' => 'SAN JUAN'],
            ['codigo_municipio' => 13, 'id_departamento' => 10, 'nombre' => 'SAN MARCOS DE LA SIERRA'],
            ['codigo_municipio' => 14, 'id_departamento' => 10, 'nombre' => 'SAN MIGUELITO'],
            ['codigo_municipio' => 15, 'id_departamento' => 10, 'nombre' => 'SANTA LUCIA'],
            ['codigo_municipio' => 16, 'id_departamento' => 10, 'nombre' => 'YAMARANGUILA'],
            ['codigo_municipio' => 17, 'id_departamento' => 10, 'nombre' => 'SAN FRANCISCO DE OPALACA'],
            ['codigo_municipio' => 1, 'id_departamento' => 11, 'nombre' => 'ROATAN'],
            ['codigo_municipio' => 2, 'id_departamento' => 11, 'nombre' => 'GUANAJA'],
            ['codigo_municipio' => 3, 'id_departamento' => 11, 'nombre' => 'UTILA'],
            ['codigo_municipio' => 4, 'id_departamento' => 11, 'nombre' => 'JOSE SANTOS GUARDIOLA'],
            ['codigo_municipio' => 1, 'id_departamento' => 12, 'nombre' => 'LA PAZ'],
            ['codigo_municipio' => 2, 'id_departamento' => 12, 'nombre' => 'AGUANQUETERIQUE'],
            ['codigo_municipio' => 3, 'id_departamento' => 12, 'nombre' => 'CABANAS SEMILATON'],
            ['codigo_municipio' => 4, 'id_departamento' => 12, 'nombre' => 'CANE'],
            ['codigo_municipio' => 5, 'id_departamento' => 12, 'nombre' => 'CHINACLA'],
            ['codigo_municipio' => 6, 'id_departamento' => 12, 'nombre' => 'SAN ANTONIO DEL NORTE'],
            ['codigo_municipio' => 7, 'id_departamento' => 12, 'nombre' => 'GUAJIQUIRO'],
            ['codigo_municipio' => 8, 'id_departamento' => 12, 'nombre' => 'LAUTERIQUE'],
            ['codigo_municipio' => 9, 'id_departamento' => 12, 'nombre' => 'MARCALA'],
            ['codigo_municipio' => 10, 'id_departamento' => 12, 'nombre' => 'MERCEDES DE ORIENTE'],
            ['codigo_municipio' => 11, 'id_departamento' => 12, 'nombre' => 'OPATORO'],
            ['codigo_municipio' => 12, 'id_departamento' => 12, 'nombre' => 'SAN JOSE'],
            ['codigo_municipio' => 13, 'id_departamento' => 12, 'nombre' => 'SAN JUAN'],
            ['codigo_municipio' => 14, 'id_departamento' => 12, 'nombre' => 'SANTA  ANA'],
            ['codigo_municipio' => 15, 'id_departamento' => 12, 'nombre' => 'SANTA ELENA'],
            ['codigo_municipio' => 16, 'id_departamento' => 12, 'nombre' => 'SANTA MARIA'],
            ['codigo_municipio' => 17, 'id_departamento' => 12, 'nombre' => 'SANTIAGO DE PURINGLA'],
            ['codigo_municipio' => 18, 'id_departamento' => 12, 'nombre' => 'SAN PEDRO DE TUTULE'],
            ['codigo_municipio' => 19, 'id_departamento' => 12, 'nombre' => 'YARULA'],
            ['codigo_municipio' => 1, 'id_departamento' => 13, 'nombre' => ' GRACIAS'],
            ['codigo_municipio' => 2, 'id_departamento' => 13, 'nombre' => 'BELEN'],
            ['codigo_municipio' => 3, 'id_departamento' => 13, 'nombre' => 'CANDELARIA'],
            ['codigo_municipio' => 4, 'id_departamento' => 13, 'nombre' => 'SAN MANUEL COLOHETE'],
            ['codigo_municipio' => 5, 'id_departamento' => 13, 'nombre' => 'COLOLACA'],
            ['codigo_municipio' => 6, 'id_departamento' => 13, 'nombre' => 'ERANDIQUE'],
            ['codigo_municipio' => 7, 'id_departamento' => 13, 'nombre' => 'GUALCINCE'],
            ['codigo_municipio' => 8, 'id_departamento' => 13, 'nombre' => 'GUARITA'],
            ['codigo_municipio' => 9, 'id_departamento' => 13, 'nombre' => 'LA CAMPA'],
            ['codigo_municipio' => 10, 'id_departamento' => 13, 'nombre' => 'LA IGUALA'],
            ['codigo_municipio' => 11, 'id_departamento' => 13, 'nombre' => 'LAS FLORES'],
            ['codigo_municipio' => 12, 'id_departamento' => 13, 'nombre' => 'LA UNION'],
            ['codigo_municipio' => 13, 'id_departamento' => 13, 'nombre' => 'LA VIRTUD'],
            ['codigo_municipio' => 14, 'id_departamento' => 13, 'nombre' => 'LEPAERA'],
            ['codigo_municipio' => 15, 'id_departamento' => 13, 'nombre' => 'MAPULACA'],
            ['codigo_municipio' => 16, 'id_departamento' => 13, 'nombre' => 'PIRAERA'],
            ['codigo_municipio' => 17, 'id_departamento' => 13, 'nombre' => 'SAN ANDRES'],
            ['codigo_municipio' => 18, 'id_departamento' => 13, 'nombre' => 'SAN FRANCISCO'],
            ['codigo_municipio' => 19, 'id_departamento' => 13, 'nombre' => 'SAN JUAN DE GUARITA'],
            ['codigo_municipio' => 20, 'id_departamento' => 13, 'nombre' => 'SAN RAFAEL'],
            ['codigo_municipio' => 21, 'id_departamento' => 13, 'nombre' => 'SAN SEBASTIAN'],
            ['codigo_municipio' => 22, 'id_departamento' => 13, 'nombre' => 'SANTA CRUZ'],
            ['codigo_municipio' => 23, 'id_departamento' => 13, 'nombre' => 'TALGUA'],
            ['codigo_municipio' => 24, 'id_departamento' => 13, 'nombre' => 'TAMBLA'],
            ['codigo_municipio' => 25, 'id_departamento' => 13, 'nombre' => 'TOMALA'],
            ['codigo_municipio' => 26, 'id_departamento' => 13, 'nombre' => 'VALLADOLID'],
            ['codigo_municipio' => 27, 'id_departamento' => 13, 'nombre' => 'VIRGINIA'],
            ['codigo_municipio' => 28, 'id_departamento' => 13, 'nombre' => 'CAIQUIN'],
            ['codigo_municipio' => 1, 'id_departamento' => 14, 'nombre' => 'NUEVA OCOTEPEQUE'],
            ['codigo_municipio' => 2, 'id_departamento' => 14, 'nombre' => 'BELEN GUALCHO'],
            ['codigo_municipio' => 3, 'id_departamento' => 14, 'nombre' => 'CONCEPCION'],
            ['codigo_municipio' => 4, 'id_departamento' => 14, 'nombre' => 'DOLORES MERENDON'],
            ['codigo_municipio' => 5, 'id_departamento' => 14, 'nombre' => 'FRATERNIDAD'],
            ['codigo_municipio' => 6, 'id_departamento' => 14, 'nombre' => 'LA ENCARNACION'],
            ['codigo_municipio' => 7, 'id_departamento' => 14, 'nombre' => 'LA LABOR'],
            ['codigo_municipio' => 8, 'id_departamento' => 14, 'nombre' => 'LUCERNA'],
            ['codigo_municipio' => 9, 'id_departamento' => 14, 'nombre' => 'MERCEDES'],
            ['codigo_municipio' => 10, 'id_departamento' => 14, 'nombre' => 'SAN FERNANDO'],
            ['codigo_municipio' => 11, 'id_departamento' => 14, 'nombre' => 'SAN FRANCISCO'],
            ['codigo_municipio' => 12, 'id_departamento' => 14, 'nombre' => 'SAN JORGE'],
            ['codigo_municipio' => 13, 'id_departamento' => 14, 'nombre' => 'SAN MARCOS'],
            ['codigo_municipio' => 14, 'id_departamento' => 14, 'nombre' => 'SANTA FE'],
            ['codigo_municipio' => 15, 'id_departamento' => 14, 'nombre' => 'SENSENTI'],
            ['codigo_municipio' => 16, 'id_departamento' => 14, 'nombre' => 'SINUAPA'],
            ['codigo_municipio' => 17, 'id_departamento' => 14, 'nombre' => 'OCOTEPEQUE'],
            ['codigo_municipio' => 1, 'id_departamento' => 15, 'nombre' => 'JUTICALPA'],
            ['codigo_municipio' => 2, 'id_departamento' => 15, 'nombre' => 'CAMPAMENTO'],
            ['codigo_municipio' => 3, 'id_departamento' => 15, 'nombre' => 'CATACAMAS'],
            ['codigo_municipio' => 4, 'id_departamento' => 15, 'nombre' => 'CONCORDIA'],
            ['codigo_municipio' => 5, 'id_departamento' => 15, 'nombre' => 'DULCE NOMBRE DE CULMI'],
            ['codigo_municipio' => 6, 'id_departamento' => 15, 'nombre' => 'SANTA MARIA DEL REAL'],
            ['codigo_municipio' => 7, 'id_departamento' => 15, 'nombre' => 'EL ROSARIO'],
            ['codigo_municipio' => 8, 'id_departamento' => 15, 'nombre' => 'ESQUIPULAS DEL NORTE'],
            ['codigo_municipio' => 9, 'id_departamento' => 15, 'nombre' => 'GUALACO'],
            ['codigo_municipio' => 10, 'id_departamento' => 15, 'nombre' => 'GUARIZAMA'],
            ['codigo_municipio' => 11, 'id_departamento' => 15, 'nombre' => 'GUATA'],
            ['codigo_municipio' => 12, 'id_departamento' => 15, 'nombre' => 'GUAYAPE'],
            ['codigo_municipio' => 13, 'id_departamento' => 15, 'nombre' => 'JANO'],
            ['codigo_municipio' => 14, 'id_departamento' => 15, 'nombre' => 'LA UNION'],
            ['codigo_municipio' => 15, 'id_departamento' => 15, 'nombre' => 'MANGULILE'],
            ['codigo_municipio' => 16, 'id_departamento' => 15, 'nombre' => 'MANTO'],
            ['codigo_municipio' => 17, 'id_departamento' => 15, 'nombre' => 'SALAMA'],
            ['codigo_municipio' => 18, 'id_departamento' => 15, 'nombre' => 'SAN ESTEBAN'],
            ['codigo_municipio' => 19, 'id_departamento' => 15, 'nombre' => 'SAN FRANCISCO DE BECERRA'],
            ['codigo_municipio' => 20, 'id_departamento' => 15, 'nombre' => 'SAN FRANCISCO DE LAPAZ'],
            ['codigo_municipio' => 21, 'id_departamento' => 15, 'nombre' => 'SILCA'],
            ['codigo_municipio' => 22, 'id_departamento' => 15, 'nombre' => 'YOCON'],
            ['codigo_municipio' => 23, 'id_departamento' => 15, 'nombre' => 'PATUCA'],
            ['codigo_municipio' => 1, 'id_departamento' => 16, 'nombre' => 'SANTA BARBARA'],
            ['codigo_municipio' => 2, 'id_departamento' => 16, 'nombre' => 'LA ARADA'],
            ['codigo_municipio' => 3, 'id_departamento' => 16, 'nombre' => 'ATIMA'],
            ['codigo_municipio' => 4, 'id_departamento' => 16, 'nombre' => 'CEGUACA'],
            ['codigo_municipio' => 5, 'id_departamento' => 16, 'nombre' => 'SAN JOSE COLINAS'],
            ['codigo_municipio' => 6, 'id_departamento' => 16, 'nombre' => 'CONCEPCION DEL NORTE'],
            ['codigo_municipio' => 7, 'id_departamento' => 16, 'nombre' => 'CONCEPCION DEL SUR'],
            ['codigo_municipio' => 8, 'id_departamento' => 16, 'nombre' => 'CHINDA'],
            ['codigo_municipio' => 9, 'id_departamento' => 16, 'nombre' => 'EL NISPERO'],
            ['codigo_municipio' => 10, 'id_departamento' => 16, 'nombre' => 'GUALALA'],
            ['codigo_municipio' => 11, 'id_departamento' => 16, 'nombre' => 'ILAMA'],
            ['codigo_municipio' => 12, 'id_departamento' => 16, 'nombre' => 'MACUELIZO'],
            ['codigo_municipio' => 13, 'id_departamento' => 16, 'nombre' => 'NARANJITO'],
            ['codigo_municipio' => 14, 'id_departamento' => 16, 'nombre' => 'NUEVA CELILAC'],
            ['codigo_municipio' => 15, 'id_departamento' => 16, 'nombre' => 'PETOA'],
            ['codigo_municipio' => 16, 'id_departamento' => 16, 'nombre' => 'PROTECCION'],
            ['codigo_municipio' => 17, 'id_departamento' => 16, 'nombre' => 'QUIMISTAN'],
            ['codigo_municipio' => 18, 'id_departamento' => 16, 'nombre' => 'SAN FRANCISCO DE OJUERA'],
            ['codigo_municipio' => 19, 'id_departamento' => 16, 'nombre' => 'SAN LUIS'],
            ['codigo_municipio' => 20, 'id_departamento' => 16, 'nombre' => 'SAN MARCOS'],
            ['codigo_municipio' => 21, 'id_departamento' => 16, 'nombre' => 'SAN NICOLAS'],
            ['codigo_municipio' => 22, 'id_departamento' => 16, 'nombre' => 'SANTA RITA'],
            ['codigo_municipio' => 23, 'id_departamento' => 16, 'nombre' => 'TRINIDAD'],
            ['codigo_municipio' => 24, 'id_departamento' => 16, 'nombre' => 'SAN VICENTE CENTENARIO'],
            ['codigo_municipio' => 25, 'id_departamento' => 16, 'nombre' => 'SAN PEDRO ZACAPA'],
            ['codigo_municipio' => 26, 'id_departamento' => 16, 'nombre' => 'AZACUALPA'],
            ['codigo_municipio' => 27, 'id_departamento' => 16, 'nombre' => 'LAS VEGAS'],
            ['codigo_municipio' => 28, 'id_departamento' => 16, 'nombre' => 'NUEVA FRONTERA'],
            ['codigo_municipio' => 1, 'id_departamento' => 17, 'nombre' => 'NACAOME'],
            ['codigo_municipio' => 2, 'id_departamento' => 17, 'nombre' => 'ALIANZA'],
            ['codigo_municipio' => 3, 'id_departamento' => 17, 'nombre' => 'AMAPALA'],
            ['codigo_municipio' => 4, 'id_departamento' => 17, 'nombre' => 'ARAMECINA'],
            ['codigo_municipio' => 5, 'id_departamento' => 17, 'nombre' => 'CARIDAD'],
            ['codigo_municipio' => 6, 'id_departamento' => 17, 'nombre' => 'GOASCORAN'],
            ['codigo_municipio' => 7, 'id_departamento' => 17, 'nombre' => 'LANGUE'],
            ['codigo_municipio' => 8, 'id_departamento' => 17, 'nombre' => 'SAN LORENZO'],
            ['codigo_municipio' => 9, 'id_departamento' => 17, 'nombre' => 'SAN LORENZO'],
            ['codigo_municipio' => 10, 'id_departamento' => 17, 'nombre' => 'GOASCORAN'],
            ['codigo_municipio' => 11, 'id_departamento' => 17, 'nombre' => 'LANGUE'],
            ['codigo_municipio' => 12, 'id_departamento' => 17, 'nombre' => 'SAN LORENZO'],
            ['codigo_municipio' => 13, 'id_departamento' => 17, 'nombre' => 'SAN FRANCISCO DE CORAY'],
            ['codigo_municipio' => 1, 'id_departamento' => 18, 'nombre' => 'YORO'],
            ['codigo_municipio' => 2, 'id_departamento' => 18, 'nombre' => 'ARENAL'],
            ['codigo_municipio' => 3, 'id_departamento' => 18, 'nombre' => 'EL NEGRITO'],
            ['codigo_municipio' => 4, 'id_departamento' => 18, 'nombre' => 'EL PROGRESO'],
            ['codigo_municipio' => 5, 'id_departamento' => 18, 'nombre' => 'JOCON'],
            ['codigo_municipio' => 6, 'id_departamento' => 18, 'nombre' => 'MORAZAN'],
            ['codigo_municipio' => 7, 'id_departamento' => 18, 'nombre' => 'OLANCHITO'],
            ['codigo_municipio' => 8, 'id_departamento' => 18, 'nombre' => 'SULACO'],
            ['codigo_municipio' => 9, 'id_departamento' => 18, 'nombre' => 'VICTORIA'],
            ['codigo_municipio' => 10, 'id_departamento' => 18, 'nombre' => 'YORITO'],
            ['codigo_municipio' => 11, 'id_departamento' => 18, 'nombre' => 'SANTA RITA'],
        ]);
    }
}
